<a href="https://colab.research.google.com/github/Seunsoipe/R/blob/main/Bivariate_Analysis_Checkpoint_Python_Version.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Objective

We will continue the work on the same dataset of the previous checkpoint, but we will go deeper and study the relation between average_montly_hours and number_project.

Instructions

1. Load the dataset

2. Compute the Correlation coefficient with R and python and deduce its value

3. In the second step, we are going to implement a linear regression of 
average_montly_hours = a*number_project+b

4. Deduce the final expression of our regression

Don’t forget to implement your work with both R and python

In [12]:
import pandas as pd

In [9]:
from google.colab import files


uploaded = files.upload()

Saving HR_comma_sep.csv to HR_comma_sep (2).csv


In [13]:
data = pd.read_csv('HR_comma_sep.csv')


In [14]:
data

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years    sales  salary  
0                          0    sales     low  
1                          0    sales  medium  
2                          0    sales  medium  
3                          0    sales     low  
4                          0    sales     low  
...                      ...      ...     ...  
14994                      0  support     low  
14995                      0  support     low  
14996                      0  support     low  
14997                      0  support     low  
14998                      0  support     low  

[14999 rows x 10 columns]

In [16]:
#Computation of the  Correlation coefficient

import numpy as np

np.corrcoef(data['average_montly_hours'], data['number_project'])

array([[1.        , 0.41721063],
       [0.41721063, 1.        ]])

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
linearReg = LinearRegression()

In [21]:

#implement a linear regression of average_montly_hours = a*number_project+b

model = LinearRegression().fit(np.array(data['average_montly_hours']).reshape(14999,1),
                               np.array(data['number_project']).reshape(14999,1))

In [23]:
model.predict([[100]])

array([[2.76256545]])

In [24]:
model.predict([[150]])

array([[3.27740197]])

In [25]:
model.predict([[350]])

array([[5.33674809]])

In [26]:
print('intercept:', model.intercept_)
print('coef:', model.coef_)

intercept: [1.73289239]
coef: [[0.01029673]]


In [34]:
#The expression of this regression will be expressed as:

#number_project = model.intercept_ + model.coef_ * average_montly_hours

In [35]:
test_at_100 = 1.73289239 + 0.01029673 * 100

test_at_100

2.76256539